services:
  byedpi:
    image: tazihad/byedpi
    container_name: byedpi
    restart: unless-stopped
    ports:
      - "127.0.0.1:1080:1080"
    # Аргументы передаются списком, чтобы избежать проблем с кавычками
    command:
      - "--disorder"
      - "3"             # Увеличиваем дистанцию перемешивания
      - "--split"
      - "1+"            # Дробим с первого байта и далее (итеративно)
      - "--fake"        # Отправляем фейк-пакет
      - "-1"            # -1 часто работает лучше фиксированного числа для обхода кеша DPI
      - "--ttl"
      - "8"             # Чуть выше TTL, чтобы фейк гарантированно прошел первый узел провайдера
      - "--fake-sni"
      - "speedtest.net" # Меняем на более «бытовой» домен
      - "--oob"
      - "1"             # Добавляем Out-of-Band данные (мощный дестабилизатор)
      - "--debug"
      - "1"             # Ставим 1, чтобы логи не забивали диск, если все работает
    healthcheck:
      test: ["CMD-SHELL", "curl -s -x socks5h://127.0.0.1:1080 http://www.google.com --connect-timeout 2 > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
