services:
  byedpi:
    image: tazihad/byedpi
    container_name: byedpi
    restart: unless-stopped
    ports:
      - "1080:1080"
    # Аргументы передаются списком, чтобы избежать проблем с кавычками
    command:
      - "--split"
      - "1"
      - "--fake"
      - "-1"
      - "--ttl"
      - "3"             # Уменьшаем до 3 (фейк должен быть очень коротким, чтобы только "ослепить" ТСПУ)
      - "--fake-sni"
      - "vk.com"        # Меняем на vk.com (он гарантированно в белом списке и не вызывает подозрений)
      - "--mod-http"
      - "hcsm"
      - "--debug"
      - "1"
    healthcheck:
      test: ["CMD-SHELL", "curl -s -x socks5h://127.0.0.1:1080 http://www.google.com --connect-timeout 2 > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
