name: Update Stack Config

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docker-compose.yaml' # Сработает ТОЛЬКО при изменении этого файла
  workflow_dispatch: 

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Webhook
        run: |
          curl --retry 3 \
               --retry-delay 5 \
               --max-time 30 \
               -X POST "${{ secrets.DEPLOY_WEBHOOK_URL }}"
